import NavBar from '@/components/navigation/nav'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/footer'


const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='overflow-hidden'>
          <div className='z-10'>
            <NavBar />
          </div>
          {children}
          <Footer />

        </main>
      </body>
    </html>
  )
}
